### ISSUE TITLE
Gnu Hello demo doesnt work on windows

### ISSUE THREAD

**Issue by pmiess** [0install/web-site#3]
When I run the example 0Compile on windows I get the following.

>0compile autocompile http://0install.net/tests/GNU-Hello.xml
================= http://0install.net/tests/GNU-Hello.xml ==================

Selecting versions for GNU Hello...
Selection done.

Plan:

- GNU Hello: Compile 1.3 (sha1=2aae32fd27d194167eac7eb611d7ce0983f83dd7)
  - make: Use existing binary 3.81 (Windows-i486)
    - make dependencies: Use existing binary 3.81 (Windows-i486)

No dependencies need compiling... compile GNU Hello itself...
No manifest digest for implementation 'sha1=2aae32fd27d194167eac7eb611d7ce0983f83dd7' found.
Download with external fetcher failed

A manifest-digest element is needed.

**Comment by talex5** [comment]
@bastianeicher says:

> Zero Install for Windows does not support the old “sha1” digest format anymore. It only supports “sha1new”, “sha256” and “sha256new”.

I've added a sha256 digest to the feed now, so it should work.
